name: "Strategy Submission"
description: "Submit a new roulette strategy to the community collection"
title: "feat(strategy): add [strategy name]"
labels: ["strategy-submission", "community"]
assignees: []

body:
  - type: input
    id: strategy_name
    attributes:
      label: Strategy Name
      description: Provide a clear, descriptive name for your strategy
      placeholder: "e.g., My Martingale"
    validations:
      required: true

  - type: input
    id: contributor
    attributes:
      label: Your Name/Handle
      description: How would you like to be credited as the contributor?
      placeholder: "e.g., johndoe"
    validations:
      required: true

  - type: textarea
    id: strategy_description
    attributes:
      label: Strategy Description
      description: Provide a detailed description of how your strategy works
      placeholder: "Describe your strategy in detail"
    validations:
      required: true

  - type: input
    id: strategy_type
    attributes:
      label: Strategy Type
      description: e.g., Martingale, Progressive, Flat Betting, Custom
      placeholder: "e.g., Martingale"
    validations:
      required: true

