name: "🎲 Strategy Submission"
description: "Submit a new roulette strategy to the community collection"
title: "feat(strategy): add [strategy name]"
labels:
  - strategy-submission
  - community
assignees: []

body:
  - type: input
    id: strategy_name
    attributes:
      label: Strategy Name
      description: Provide a clear, descriptive name for your strategy
      placeholder: "e.g., My Martingale"
    validations:
      required: true

  - type: input
    id: contributor
    attributes:
      label: Your Name/Handle
      description: How would you like to be credited as the contributor?
      placeholder: "e.g., johndoe"
    validations:
      required: true

  - type: textarea
    id: strategy_description
    attributes:
      label: Strategy Description
      description: Provide a detailed description of how your strategy works
      placeholder: "Describe your strategy in detail"
    validations:
      required: true

  - type: input
    id: strategy_type
    attributes:
      label: Strategy Type
      description: e.g., Martingale, Progressive, Flat Betting, Custom
      placeholder: "e.g., Martingale"
    validations:
      required: true

  - type: dropdown
    id: risk_level
    attributes:
      label: Risk Level
      description: Select the risk level of your strategy
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true

  - type: input
    id: default_bankroll
    attributes:
      label: Default Bankroll ($)
      description: Default bankroll amount
      placeholder: "e.g., 1000"
    validations:
      required: true

  - type: input
    id: default_base_bet
    attributes:
      label: Default Base Bet ($)
      description: Default base bet amount
      placeholder: "e.g., 10"
    validations:
      required: true

  - type: input
    id: default_target_profit
    attributes:
      label: Default Target Profit ($)
      description: Default target profit amount
      placeholder: "e.g., 100"
    validations:
      required: true

  - type: textarea
    id: special_features
    attributes:
      label: Special Features
      description: Any unique aspects of your strategy (loss limits, win streaks, etc.)
      placeholder: "Describe any special features"
    validations:
      required: false

  - type: input
    id: strategy_file
    attributes:
      label: Strategy File
      description: What will you name your strategy file? (e.g., my_martingale.py)
      placeholder: "e.g., my_martingale.py"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Any special imports or dependencies beyond the core framework
      placeholder: "List any dependencies"
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Have you tested this strategy? What were the results?
      placeholder: "Describe your testing process and results"
    validations:
      required: false

  - type: textarea
    id: code_preview
    attributes:
      label: Code Preview
      description: Paste a preview of your strategy's place_bet method or key logic
      render: python
      placeholder: |
        def place_bet(self, game_state):
            # Your implementation here
            pass
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please ensure:
      options:
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I have tested my strategy with the core framework
          required: true
        - label: My strategy includes proper error handling
          required: true
        - label: I have provided clear documentation in docstrings
          required: true
        - label: My strategy follows the [Strategy Development Guide](../docs/strategy-development.md)
          required: true
        - label: I have included appropriate default values in `get_defaults()`
          required: true
        - label: My code follows the project's coding standards
          required: true
        - label: I am willing to maintain this strategy and respond to issues
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the strategy here
      placeholder: "Any additional information"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** After creating this issue, you'll need to submit a Pull Request with your strategy implementation. See our [Contributing Guidelines](../CONTRIBUTING.md) for detailed instructions.