name: "Strategy Submission"
description: "Submit a new roulette strategy to the community collection"
title: "feat(strategy): add [strategy name]"
labels: ["strategy-submission", "community"]
assignees: []

body:
  - type: input
    id: strategy_name
    attributes:
      label: Strategy Name
      description: Provide a clear, descriptive name for your strategy
      placeholder: "e.g., My Martingale"
    validations:
      required: true

