name: "Strategy Submission"
description: "Submit a new roulette strategy to the community collection"
title: "feat(strategy): add [strategy name]"
labels: ["strategy-submission", "community"]
assignees: []

body:
  - type: input
    id: strategy_name
    attributes:
      label: Strategy Name
      description: Provide a clear, descriptive name for your strategy
      placeholder: "e.g., Marty's Secret Martingale"
    validations:
      required: true

  - type: input
    id: contributor
    attributes:
      label: Your Name/Handle
      description: How would you like to be credited as the contributor?
      placeholder: "e.g., johndoe"
    validations:
      required: true
      
  - type: input
    id: default_bankroll
    attributes:
      label: Default Bankroll ($)
      description: Default bankroll amount
      placeholder: "e.g., 1000"
    validations:
      required: true

  - type: input
    id: default_base_bet
    attributes:
      label: Default Base Bet ($)
      description: Default base bet amount
      placeholder: "e.g., 10"
    validations:
      required: true

  - type: input
    id: default_target_profit
    attributes:
      label: Default Target Profit ($)
      description: Default target profit amount
      placeholder: "e.g., 100"
    validations:
      required: true

  - type: textarea
    id: strategy_description
    attributes:
      label: Strategy Description
      description: Provide a detailed description of how your strategy works
      placeholder: "Describe your strategy in detail"
    validations:
      required: true

  - type: dropdown
    id: strategy_type
    attributes:
      label: Strategy Type
      description: Select one or more types that best describe your strategy. If "Custom", specify below.
      multiple: true
      options:
        - Martingale
        - Fibonacci
        - Reverse Martingale
        - Progressive
        - Flat Betting
        - D'Alembert
        - Pattern Recognition
        - Custom
    validations:
      required: true

  - type: input
    id: custom_strategy_type
    attributes:
      label: Custom Strategy Type
      description: If you selected "Custom" above, please specify your strategy type here
      placeholder: "e.g., Labouchere, Secret Sauce"
    validations:
      required: false

  - type: input
    id: strategy_video
    attributes:
      label: Strategy Video Link
      description: Optionally provide a link to a video demonstrating your strategy (YouTube, Vimeo, etc.)
      placeholder: "e.g., https://youtu.be/example"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the strategy here
      placeholder: "Any additional information"
    validations:
      required: false